"""EMV sizes and the Book 2 layout of recovered data, named as in circuits/emv/src/card_chain.nr."""

BITS_PER_BYTE = 8
NIBBLE_BIT_LEN = 4
NIBBLES_PER_BYTE = BITS_PER_BYTE // NIBBLE_BIT_LEN
NIBBLE_PAD = "F"
DECIMAL_BASE = 10

RSA_EXPONENT = 3
HASH_ALG_SHA1 = 0x01
PK_ALG_RSA = 0x01

RECOVERED_DATA_HEADER = 0x6A
RECOVERED_DATA_TRAILER = 0xBC
PAD_BYTE = 0xBB
FMT_ISSUER_CERT = 0x02
FMT_ICC_CERT = 0x04
FMT_SDAD = {0x05: "DDA (Book 2)", 0x95: "fDDA (Visa kernel)"}

NONCE_BYTE_LEN = 4
AMOUNT_AUTHORISED_BYTE_LEN = 6
ISSUER_ID_BYTE_LEN = 4
EXPIRY_BYTE_LEN = 2
SERIAL_BYTE_LEN = 3
PAN_BYTE_LEN = 10
EXPONENT_BYTE_LEN = 1
HASH_BYTE_LEN = 20

HEADER_BYTE_LEN = 1
FORMAT_BYTE_LEN = 1
ALGORITHM_ID_BYTE_LEN = 1
LENGTH_FIELD_BYTE_LEN = 1
TRAILER_BYTE_LEN = 1
HASH_AND_TRAILER_BYTE_LEN = HASH_BYTE_LEN + TRAILER_BYTE_LEN
ENVELOPE_BYTE_LEN = HEADER_BYTE_LEN + HASH_AND_TRAILER_BYTE_LEN

HEADER_OFFSET = 0
FORMAT_OFFSET = HEADER_OFFSET + HEADER_BYTE_LEN
BODY_OFFSET = FORMAT_OFFSET
FIELDS_OFFSET = FORMAT_OFFSET + FORMAT_BYTE_LEN

# Book 2 table 6.
ISSUER_ID_OFFSET = FIELDS_OFFSET
ISSUER_EXPIRY_OFFSET = ISSUER_ID_OFFSET + ISSUER_ID_BYTE_LEN
ISSUER_SERIAL_OFFSET = ISSUER_EXPIRY_OFFSET + EXPIRY_BYTE_LEN
ISSUER_HASH_ALG_OFFSET = ISSUER_SERIAL_OFFSET + SERIAL_BYTE_LEN
ISSUER_PK_ALG_OFFSET = ISSUER_HASH_ALG_OFFSET + ALGORITHM_ID_BYTE_LEN
ISSUER_KEY_BYTE_LEN_OFFSET = ISSUER_PK_ALG_OFFSET + ALGORITHM_ID_BYTE_LEN
ISSUER_EXPONENT_BYTE_LEN_OFFSET = ISSUER_KEY_BYTE_LEN_OFFSET + LENGTH_FIELD_BYTE_LEN
ISSUER_KEY_OFFSET = ISSUER_EXPONENT_BYTE_LEN_OFFSET + LENGTH_FIELD_BYTE_LEN

# Book 2 table 14.
ICC_PAN_OFFSET = FIELDS_OFFSET
ICC_EXPIRY_OFFSET = ICC_PAN_OFFSET + PAN_BYTE_LEN
ICC_SERIAL_OFFSET = ICC_EXPIRY_OFFSET + EXPIRY_BYTE_LEN
ICC_HASH_ALG_OFFSET = ICC_SERIAL_OFFSET + SERIAL_BYTE_LEN
ICC_PK_ALG_OFFSET = ICC_HASH_ALG_OFFSET + ALGORITHM_ID_BYTE_LEN
ICC_KEY_BYTE_LEN_OFFSET = ICC_PK_ALG_OFFSET + ALGORITHM_ID_BYTE_LEN
ICC_EXPONENT_BYTE_LEN_OFFSET = ICC_KEY_BYTE_LEN_OFFSET + LENGTH_FIELD_BYTE_LEN
ICC_KEY_OFFSET = ICC_EXPONENT_BYTE_LEN_OFFSET + LENGTH_FIELD_BYTE_LEN

# Book 2 table 17.
SDAD_HASH_ALG_OFFSET = FIELDS_OFFSET
DYNAMIC_DATA_BYTE_LEN_OFFSET = SDAD_HASH_ALG_OFFSET + ALGORITHM_ID_BYTE_LEN
DYNAMIC_DATA_OFFSET = DYNAMIC_DATA_BYTE_LEN_OFFSET + LENGTH_FIELD_BYTE_LEN

# BER-TLV.
RECORD_TEMPLATE_TAG = 0x70
BER_LONG_LENGTH_FLAG = 0x80
BER_LENGTH_COUNT_MASK = 0x7F
BER_TAG_BYTE_LEN = 1
BER_LENGTH_BYTE_LEN = 1
STATUS_WORD_BYTE_LEN = 2
STATUS_WORD_SUCCESS = bytes.fromhex("9000")
AIP_TAG_LIST = bytes.fromhex("82")
