#!/usr/bin/env python3
"""Circuit inputs from the synthetic taps: <pkg>/Prover.toml and <pkg>/src/tests/vectors.nr."""

import json
import os
from typing import Any, NoReturn

import verify_emv_reference as vc
from gen_synthetic import FIXTURES, KINDS

ROOT = os.path.dirname(FIXTURES)
CA_KEYS = os.path.join(FIXTURES, "test-ca-keys.json")
TODAY = 2609  # YYMM, pinned so the committed outputs don't change every month
SCOPE = 0x5C09E  # any field element; the emv crate derives real ones

LIMB_BITS = 120
BARRETT_OVERFLOW_BITS = 6  # bignum's BARRETT_REDUCTION_OVERFLOW_BITS
MAX_STATIC_DATA_LEN = 256  # mastercard_dda's MAX_STATIC_DATA_LEN

Inputs = dict[str, Any]


def limbs(n: int, bits: int) -> list[int]:
    """120-bit little-endian limbs; the top limb absorbs any excess (redc can exceed)."""
    count = (bits + LIMB_BITS - 1) // LIMB_BITS
    out = []
    for _ in range(count - 1):
        out.append(n & ((1 << LIMB_BITS) - 1))
        n >>= LIMB_BITS
    out.append(n)
    return out


def redc(modulus: int, bits: int) -> list[int]:
    """Barrett hint. A width that is a multiple of 120 bits is held as arithmetic modulo
    2n in the circuit (emv::DoubledKey), so its hint is for 2n at one bit wider."""
    if bits % LIMB_BITS == 0:
        modulus, bits = 2 * modulus, bits + 1
    return limbs((1 << (2 * bits + BARRETT_OVERFLOW_BITS)) // modulus, bits)


def key_limbs(modulus: bytes) -> tuple[list[int], list[int]]:
    n, bits = int.from_bytes(modulus, "big"), len(modulus) * 8
    return limbs(n, bits), redc(n, bits)


def fail(pkg: str, what: str) -> NoReturn:
    raise SystemExit(f"fixtures/{pkg}.json: {what} does not verify")


def circuit_inputs(pkg: str, capks: vc.CAKeys) -> Inputs:
    doc = json.load(open(os.path.join(FIXTURES, pkg + ".json")))
    els = vc.elements(doc)

    def h(tag: str) -> bytes:
        return vc.h2b(els.get(tag, {}).get("value"))

    rid = doc["selectedAid"][:10]
    ca, issuer = b"", None
    for exp, mod, _ in capks.get((rid, els["8F"]["value"]), []):
        issuer, _ = vc.verify_issuer_cert(h("90"), mod, exp, h("92"), h("9F32"))
        if issuer:
            ca = mod
            break
    if not issuer:
        fail(pkg, "issuer certificate")
    static = vc.static_data_to_authenticate(doc, els)
    icc, _ = vc.verify_icc_cert(h("9F46"), issuer["modulus"], issuer["exponent"], h("9F48"), h("9F47"), static)
    if not icc or not icc["hash_ok"]:
        fail(pkg, "ICC certificate")

    t = doc["terminal"]
    un, amount, currency = (bytes(t[k]) for k in ("unpredictableNumber", "amountAuthorised", "currencyCode"))
    td = un + amount + currency + h("9F69") if pkg == "visa_fdda" else un
    sd, _ = vc.verify_sdad(h("9F4B"), icc["modulus"], icc["exponent"], [("", td)])
    if not sd or not sd["matched"]:
        fail(pkg, "signed dynamic data")

    ca_modulus, ca_redc = key_limbs(ca)
    x = {
        "ca_modulus": ca_modulus,
        "nonce": list(un),
        "ca_redc": ca_redc,
        "issuer_redc": key_limbs(issuer["modulus"])[1],
        "icc_redc": key_limbs(icc["modulus"])[1],
        "issuer_cert": list(h("90")),
        "issuer_exponent": h("9F32")[0],
        "icc_cert": list(h("9F46")),
        "icc_exponent": h("9F47")[0],
        "sdad": list(h("9F4B")),
    }
    if pkg == "visa_fdda":
        x.update(amount=list(amount), currency=list(currency), card_auth_data=list(h("9F69")))
    else:
        assert len(static) <= MAX_STATIC_DATA_LEN
        x.update(issuer_remainder=list(h("92")), static_data={"storage": list(static) + [0] * (MAX_STATIC_DATA_LEN - len(static)), "len": len(static)})
    x["today"] = TODAY
    x["scope"] = SCOPE
    x["icc_modulus"] = list(icc["modulus"])
    return x


def toml_value(v: Any) -> str:
    if isinstance(v, list):
        return "[" + ", ".join(f'"{i}"' if i >= 1 << 63 else str(i) for i in v) + "]"
    return f'"{v}"' if isinstance(v, int) and v >= 1 << 63 else str(v)


def to_toml(x: Inputs) -> str:
    lines, tables = [], []
    for k, v in x.items():
        if isinstance(v, dict):
            tables.append(f"\n[{k}]\n" + "\n".join(f"{a} = {toml_value(b)}" for a, b in v.items()))
        else:
            lines.append(f"{k} = {toml_value(v)}")
    return "\n".join(lines) + "".join(tables) + "\n"


def noir_value(v: Any) -> str:
    if isinstance(v, dict):
        return f"BoundedVec::from_parts({noir_value(v['storage'])}, {v['len']})"
    if isinstance(v, list):
        return "[" + ", ".join(hex(i) for i in v) + "]"
    return hex(v)


def to_noir(name: str, x: Inputs, icc_modulus: list[int]) -> str:
    out = [
        "// Generated by scripts/gen_circuit_inputs.py from the synthetic taps in fixtures/.",
        "use crate::Inputs;",
        "",
        f"pub global ICC_MODULUS: [u8; {len(icc_modulus)}] = {noir_value(icc_modulus)};",
        "",
        "pub global CARDS: [Inputs; 1] = [",
        f"    // {name}",
        "    Inputs {",
    ]
    out += [f"        {k}: {noir_value(v)}," for k, v in x.items()]
    out += ["    },", "];"]
    return "\n".join(out) + "\n"


def struct_fields(pkg: str) -> list[str]:
    main_nr = open(os.path.join(ROOT, pkg, "src", "main.nr")).read()
    body = main_nr.split("pub struct Inputs {")[1].split("}")[0]
    return [line.split(":")[0].strip().removeprefix("pub ") for line in body.strip().splitlines()]


def main() -> None:
    capks = vc.load_CA_pubkeys(CA_KEYS)
    inputs = {pkg: circuit_inputs(pkg, capks) for pkg in KINDS}
    for pkg, x in inputs.items():
        icc_modulus = x.pop("icc_modulus")
        open(os.path.join(ROOT, pkg, "Prover.toml"), "w").write(to_toml(x))
        ordered = {k: x[k] for k in struct_fields(pkg)}
        open(os.path.join(ROOT, pkg, "src", "tests", "vectors.nr"), "w").write(to_noir(pkg, ordered, icc_modulus))
        print(f"wrote {pkg}/Prover.toml, {pkg}/src/tests/vectors.nr")


if __name__ == "__main__":
    main()
